# Generated by Django 5.0.2 on 2024-02-18 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='images/course/')),
                ('is_active', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('teacher', models.CharField(max_length=100)),
                ('discount', models.IntegerField()),
                ('season', models.IntegerField()),
                ('duration', models.CharField(max_length=100)),
                ('class_des', models.CharField(default='course', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productcategorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='PopularModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_product', to='product.productmodel')),
            ],
        ),
    ]
