# Generated by Django 5.0.2 on 2024-02-18 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productmodel_popularmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Color', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SizeProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size', models.CharField(max_length=120)),
            ],
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='duration',
            new_name='product_code',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='class_des',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='season',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='teacher',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image1',
            field=models.ImageField(default=1, upload_to='images/product/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image2',
            field=models.ImageField(default=1, upload_to='images/product/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image3',
            field=models.ImageField(default=1, upload_to='images/product/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image4',
            field=models.ImageField(default=1, upload_to='images/product/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image5',
            field=models.ImageField(default=1, upload_to='images/product/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='percent_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductVariantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_in_stock', models.IntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.colorproductmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productmodel')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sizeproductmodel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='productvariantmodel',
            constraint=models.UniqueConstraint(fields=('product', 'color', 'size'), name='unique_prod_color_size_combo'),
        ),
    ]
