# Generated by Django 5.0.2 on 2024-02-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_colorproductmodel_sizeproductmodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PopularModel',
            new_name='PopularProductModel',
        ),
    ]
