# Generated by Django 5.0.2 on 2024-02-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_popularmodel_popularproductmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularproductmodel',
            name='popular',
        ),
        migrations.AddField(
            model_name='popularproductmodel',
            name='popular',
            field=models.ManyToManyField(related_name='popular_product', to='product.productmodel'),
        ),
    ]
