# Generated by Django 5.0.2 on 2024-02-18 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_popularproductmodel_popular_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularproductmodel',
            name='popular',
        ),
        migrations.AddField(
            model_name='popularproductmodel',
            name='popular',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='popular_product', to='product.productmodel'),
            preserve_default=False,
        ),
    ]
