# Generated by Django 5.0.2 on 2024-02-18 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_popularproductmodel_popular_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorproductmodel',
            old_name='Color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='sizeproductmodel',
            old_name='Size',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='category',
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_product', to='product.colorproductmodel'),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color_size', to='product.productmodel'),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_product', to='product.sizeproductmodel'),
        ),
    ]
