# Generated by Django 5.0.2 on 2024-02-19 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_color_colorproductmodel_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariantmodel',
            old_name='amount_in_stock',
            new_name='quantity',
        ),
    ]
