# Generated by Django 5.0.2 on 2024-02-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_amount_in_stock_productvariantmodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_available',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
