# Generated by Django 5.0.2 on 2024-02-25 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productmodel_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_product', to='product.productcategorymodel'),
            preserve_default=False,
        ),
    ]
