# Generated by Django 5.0.2 on 2024-02-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorproductmodel',
            name='color_code',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
