# Generated by Django 5.0.2 on 2024-02-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_colorproductmodel_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategorymodel',
            name='category_title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
