# Generated by Django 5.0.2 on 2024-03-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productmodel_image4_alter_productmodel_image5'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizeproductmodel',
            name='Priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
