# Generated by Django 5.0.2 on 2024-03-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_sizeproductmodel_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizeproductmodel',
            name='Priority',
        ),
        migrations.AddField(
            model_name='sizeproductmodel',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
