# Generated by Django 5.0.2 on 2024-03-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_sizeproductmodel_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='is_available',
        ),
    ]
