# Generated by Django 5.0.2 on 2024-03-13 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_bannerhomemodel_options_and_more'),
        ('product', '0016_remove_productmodel_is_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorproductmodel',
            options={'verbose_name': 'Size Product', 'verbose_name_plural': 'Size Products'},
        ),
        migrations.AlterModelOptions(
            name='popularproductmodel',
            options={'verbose_name': 'Popular Product', 'verbose_name_plural': 'Popular Products'},
        ),
        migrations.AlterModelOptions(
            name='productcategorymodel',
            options={'verbose_name': 'Color Product', 'verbose_name_plural': 'Color Products'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productvariantmodel',
            options={'verbose_name': 'Product Variant(Stock)', 'verbose_name_plural': 'Product Variant(Stock)'},
        ),
        migrations.AlterModelOptions(
            name='sizeproductmodel',
            options={'verbose_name': 'Size Product', 'verbose_name_plural': 'Size Products'},
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=32, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.homesettingmodel')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
