# Generated by Django 5.0.3 on 2024-04-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_colorproductmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/product/'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/product/'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/product/'),
        ),
    ]
