# Generated by Django 5.0.3 on 2024-04-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_productmodel_category_alter_productmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantmodel',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
