# Generated by Django 5.0.3 on 2024-04-11 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_productmodel_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='product_code',
            new_name='product_id',
        ),
    ]
