# Generated by Django 5.0.3 on 2024-04-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_productsubcategorymodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='percent_discount',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='price',
        ),
        migrations.AddField(
            model_name='productvariantmodel',
            name='percent_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariantmodel',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
