# Generated by Django 5.0.3 on 2024-04-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_rename_product_id_productmodel_product_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantmodel',
            name='item_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
