# Generated by Django 5.0.3 on 2024-04-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_productvariantmodel_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='product_group',
            new_name='group_id',
        ),
    ]
