# Generated by Django 5.0.3 on 2024-04-11 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_rename_product_group_productmodel_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='group_id',
            new_name='product_id',
        ),
    ]
