# Generated by Django 5.0.3 on 2024-04-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_rename_group_id_productmodel_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='product_id',
            new_name='group_id',
        ),
    ]
