# Generated by Django 5.0.3 on 2024-04-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_productmodel_percent_discount_productmodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='percent_discount',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='price',
        ),
    ]
