# Generated by Django 5.0.3 on 2024-04-11 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_productmodel_percent_discount_productmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariantmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
