# Generated by Django 5.0.3 on 2024-04-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_productvariantmodel_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantmodel',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
