# Generated by Django 5.0.3 on 2024-04-14 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_alter_productmodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='productsubcategorymodel',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_product', to='product.productmodel'),
            preserve_default=False,
        ),
    ]
