# Generated by Django 5.0.3 on 2024-04-14 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_remove_productmodel_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubcategorymodel',
            name='product',
        ),
        migrations.CreateModel(
            name='AddSubCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_product', to='product.productmodel')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productsubcategorymodel')),
            ],
            options={
                'verbose_name': 'Product SubCategory',
                'verbose_name_plural': 'Product SubCategory',
            },
        ),
    ]
