# Generated by Django 5.0.3 on 2024-04-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_alter_productmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='image5',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='images',
            field=models.FileField(default=1, upload_to='images/zip/'),
            preserve_default=False,
        ),
    ]
