# Generated by Django 5.0.3 on 2024-04-21 11:14

import django.db.models.deletion
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_remove_productmodel_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='images',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='zip_import',
            field=models.FileField(blank=True, upload_to=product.models.upload_to),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='galleries')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.productmodel')),
            ],
        ),
    ]
