# Generated by Django 5.0.3 on 2024-04-21 14:54

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_remove_productmodel_images_productmodel_zip_import_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantmodel',
            name='zip_import',
            field=models.FileField(blank=True, null=True, upload_to=product.models.upload_to),
        ),
    ]
