# Generated by Django 5.0.3 on 2024-04-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0050_productvariantmodel_zip_import'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='zip_import',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product/cover/'),
        ),
    ]
