# Generated by Django 5.0.3 on 2024-04-21 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_remove_productmodel_zip_import_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.productvariantmodel'),
        ),
    ]
