# Generated by Django 5.0.3 on 2024-04-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_alter_galleryimage_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantmodel',
            name='zip_import',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product/description/'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='size_table_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product/size_table/'),
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
