# Generated by Django 5.0.3 on 2024-04-23 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0053_remove_productvariantmodel_zip_import_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGenderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Product Gender',
                'verbose_name_plural': 'Product Gender',
            },
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='category',
        ),
        migrations.CreateModel(
            name='AddCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productcategorymodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_product', to='product.productmodel')),
            ],
        ),
        migrations.AddField(
            model_name='productmodel',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gender_product', to='product.productgendermodel'),
        ),
    ]
