# Generated by Django 5.0.3 on 2024-04-23 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_productgendermodel_remove_productmodel_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImageGalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/product/gallery/')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_product_image', to='product.colorproductmodel')),
            ],
            options={
                'verbose_name': 'Product SubCategory',
                'verbose_name_plural': 'Product SubCategory',
            },
        ),
        migrations.CreateModel(
            name='AddImageGalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_gallery_product', to='product.productmodel')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productimagegallerymodel')),
            ],
        ),
    ]
