# Generated by Django 5.0.3 on 2024-04-23 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_productimagegallerymodel_addimagegallerymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addimagegallerymodel',
            name='image',
        ),
        migrations.AddField(
            model_name='addimagegallerymodel',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.colorproductmodel'),
            preserve_default=False,
        ),
    ]
