# Generated by Django 5.0.3 on 2024-04-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0056_remove_addimagegallerymodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addimagegallerymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product/gallery/'),
        ),
    ]
