# Generated by Django 5.0.3 on 2024-05-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0058_alter_addimagegallerymodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='application_fields',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
