# Generated by Django 5.0.3 on 2024-05-11 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0059_productmodel_application_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcategorymodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
