# Generated by Django 5.0.3 on 2024-05-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0060_addcategorymodel_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgendermodel',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productgendermodel',
            name='gender_title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productgendermodel',
            name='image',
            field=models.FileField(default=1, upload_to='images/gender/'),
            preserve_default=False,
        ),
    ]
