# Generated by Django 5.0.3 on 2024-05-12 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0061_productgendermodel_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategorymodel',
            name='category_title',
        ),
        migrations.RemoveField(
            model_name='productcategorymodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productcategorymodel',
            name='image',
        ),
    ]
