# Generated by Django 5.0.3 on 2024-05-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0062_remove_productcategorymodel_category_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='subtitle',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
