# Generated by Django 5.0.3 on 2024-05-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0063_productmodel_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
