# Generated by Django 5.0.3 on 2024-06-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0065_alter_productmodel_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('body', models.TextField()),
            ],
        ),
    ]
