# Generated by Django 5.0.3 on 2024-06-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0066_snippet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
