# Generated by Django 5.0.3 on 2024-06-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0069_imagecovermodel_remove_productmodel_cover_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageCoverModel',
        ),
    ]
