# Generated by Django 5.0.3 on 2024-06-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0070_delete_imagecovermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCoverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='images/product/cover/')),
            ],
            options={
                'verbose_name': 'Image Cover',
                'verbose_name_plural': 'Image Covers',
            },
        ),
    ]
