# Generated by Django 5.0.3 on 2024-06-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0071_imagecovermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageCoverModel',
        ),
        migrations.AddField(
            model_name='addcoverimagemodel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product/cover/'),
        ),
    ]
