# Generated by Django 5.0.3 on 2024-06-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0073_addimagegallerymodel_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addimagegallerymodel',
            name='gender',
        ),
        migrations.AddField(
            model_name='productcategorymodel',
            name='category_title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategorymodel',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategorymodel',
            name='image',
            field=models.FileField(default=1, upload_to='images/category/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product/cover/'),
        ),
        migrations.DeleteModel(
            name='AddCoverImageModel',
        ),
    ]
