# Generated by Django 5.0.3 on 2024-07-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0076_remove_productcategorymodel_category_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('service_place', models.CharField(max_length=32)),
            ],
        ),
    ]
