# Generated by Django 5.0.2 on 2024-03-08 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_addressmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressmodel',
            name='active_address',
        ),
    ]
