# Generated by Django 5.0.2 on 2024-03-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressmodel',
            old_name='VAT_number',
            new_name='emirats',
        ),
        migrations.RemoveField(
            model_name='addressmodel',
            name='address_complement',
        ),
        migrations.RemoveField(
            model_name='addressmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='addressmodel',
            name='first_name_address',
        ),
        migrations.RemoveField(
            model_name='addressmodel',
            name='identification_number',
        ),
        migrations.RemoveField(
            model_name='addressmodel',
            name='last_name_address',
        ),
        migrations.RemoveField(
            model_name='addressmodel',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='addressmodel',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='additional_information',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='address',
            field=models.TextField(),
        ),
    ]
