# Generated by Django 5.0.3 on 2024-03-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_company_name_user_trn_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='phone_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
