# Generated by Django 5.0.3 on 2024-05-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_addressmodel_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zoho_customer_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
