# Generated by Django 5.0.3 on 2024-06-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_registration_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_method',
        ),
    ]
