# Generated by Django 5.0.3 on 2024-04-12 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0005_alter_userproductmodel_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproductmodel',
            name='created',
        ),
        migrations.RemoveField(
            model_name='userproductmodel',
            name='order',
        ),
        migrations.RemoveField(
            model_name='userproductmodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='userproductmodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='userproductmodel',
            name='quantity',
        ),
    ]
