# Generated by Django 5.0.3 on 2024-04-12 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_orderitemmodel_product'),
        ('product', '0037_productvariantmodel_slug'),
        ('user_panel', '0007_remove_userproductmodel_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userproductmodel',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rel_order', to='order.ordermodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userproductmodel',
            name='price',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userproductmodel',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rel_product', to='product.productmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userproductmodel',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userproductmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rel_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
