# Generated by Django 5.0.3 on 2024-07-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(upload_to='blog/cover/')),
                ('banner', models.ImageField(upload_to='blog/banner/')),
                ('title', models.CharField(max_length=250)),
                ('title_image', models.ImageField(upload_to='blog/title/')),
                ('description', models.TextField()),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=24)),
                ('category', models.CharField(max_length=24)),
            ],
        ),
    ]
