# Generated by Django 5.0.3 on 2024-07-02 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogmodel_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
