# Generated by Django 5.0.2 on 2024-02-25 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='images/cart/setting')),
            ],
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('logo', models.ImageField(upload_to='images/social_media/')),
                ('address', models.TextField(max_length=200)),
                ('priority', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='HomeSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_title', models.CharField(max_length=100)),
                ('top_description', models.TextField()),
                ('middle_title', models.CharField(max_length=100)),
                ('middle_description', models.TextField()),
                ('up_video', models.FileField(upload_to='videos/home')),
                ('up_video_title', models.CharField(max_length=100)),
                ('up_video_description', models.TextField()),
                ('button_banner', models.ImageField(upload_to='images/home/')),
                ('middle_video', models.FileField(upload_to='videos/home')),
                ('middle_video_title', models.CharField(max_length=100)),
                ('middle_video_description', models.TextField()),
                ('banner', models.ImageField(upload_to='images/home/')),
                ('button_video', models.FileField(upload_to='videos/home')),
                ('button_video_title', models.CharField(max_length=100)),
                ('button_video_description', models.TextField()),
                ('footer_image', models.ImageField(upload_to='images/home/footer')),
            ],
        ),
        migrations.CreateModel(
            name='MiddleBannerSliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('banner', models.ImageField(upload_to='images/home/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_chart', models.ImageField(upload_to='images/product/setting')),
            ],
        ),
        migrations.CreateModel(
            name='BannerHomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/home/banner')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.homesettingmodel')),
            ],
        ),
    ]
