# Generated by Django 5.0.2 on 2024-02-26 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartsettingmodel',
            options={'verbose_name': 'Banner-Cart page', 'verbose_name_plural': 'Banner-Cart page'},
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'Number-Header', 'verbose_name_plural': 'Number-Header'},
        ),
        migrations.AlterField(
            model_name='bannerhomemodel',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_home', to='home.homesettingmodel'),
        ),
    ]
