# Generated by Django 5.0.2 on 2024-03-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_cartsettingmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesettingmodel',
            name='middle_video_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Section 5 Title'),
        ),
    ]
