# Generated by Django 5.0.2 on 2024-03-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_cartsettingmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('Message', models.TextField()),
            ],
        ),
    ]
