# Generated by Django 5.0.2 on 2024-02-26 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_middlebannerslidermodel_setting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={},
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='setting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.homesettingmodel'),
            preserve_default=False,
        ),
    ]
