# Generated by Django 5.0.2 on 2024-03-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactsubmitmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactsubmitmodel',
            old_name='Message',
            new_name='message',
        ),
    ]
