# Generated by Django 5.0.2 on 2024-03-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homesettingmodel_middle_video_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='address',
        ),
    ]
