# Generated by Django 5.0.2 on 2024-03-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_message_contactsubmitmodel_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerhomemodel',
            options={'verbose_name': 'Header Banner(Home Page)', 'verbose_name_plural': 'Header Banners(Home Page)'},
        ),
        migrations.AlterModelOptions(
            name='cartsettingmodel',
            options={'verbose_name': 'Banner(Cart page)', 'verbose_name_plural': 'Banners(Cart page)'},
        ),
        migrations.AlterModelOptions(
            name='contactsubmitmodel',
            options={'verbose_name': 'Contact User Submit', 'verbose_name_plural': 'Contact User Submit'},
        ),
        migrations.AlterModelOptions(
            name='homesettingmodel',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterModelOptions(
            name='middlebannerslidermodel',
            options={'verbose_name': 'Middle Banner Slider(Home Page)', 'verbose_name_plural': 'Middle Banner Sliders(Home Page)'},
        ),
        migrations.AlterModelOptions(
            name='productsettingmodel',
            options={'verbose_name': 'Size Chart(Shop Page)', 'verbose_name_plural': 'Size Chart(Shop Page)'},
        ),
        migrations.AlterField(
            model_name='bannerhomemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/home/banner', verbose_name='image (2218*1920 px)'),
        ),
        migrations.AlterField(
            model_name='homesettingmodel',
            name='button_banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/home/', verbose_name='Section 4 Image (1920*590 px)'),
        ),
        migrations.AlterField(
            model_name='homesettingmodel',
            name='footer_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/home/footer', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='middlebannerslidermodel',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/home/', verbose_name='image (1455*505 px)'),
        ),
        migrations.DeleteModel(
            name='ContactModel',
        ),
    ]
