# Generated by Django 5.0.2 on 2024-02-26 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contactmodel_options_contactmodel_setting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsettingmodel',
            options={'verbose_name': 'Size Chart - Shop Page', 'verbose_name_plural': 'Size Chart - Shop Page'},
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='button_video_description',
            new_name='s1_description',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='button_video_title',
            new_name='s1_title',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='middle_description',
            new_name='s2_description',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='middle_title',
            new_name='s2_title',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='button_video',
            new_name='s3_video',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='middle_video_description',
            new_name='s3_video_description',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='middle_video_title',
            new_name='s3_video_title',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='banner',
            new_name='s4_banner',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='middle_video',
            new_name='s5_video',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='top_description',
            new_name='s5_video_description',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='top_title',
            new_name='s5_video_title',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='button_banner',
            new_name='s6',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='up_video',
            new_name='s7_video',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='up_video_description',
            new_name='s7_video_description',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='up_video_title',
            new_name='s7_video_title',
        ),
        migrations.AddField(
            model_name='cartsettingmodel',
            name='setting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.homesettingmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsettingmodel',
            name='setting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.homesettingmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bannerhomemodel',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.homesettingmodel'),
        ),
    ]
