# Generated by Django 5.0.2 on 2024-03-01 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_contactmodel_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesettingmodel',
            name='middle_video_title',
        ),
    ]
