# Generated by Django 5.0.2 on 2024-02-26 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_productsettingmodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='s4_banner',
            new_name='banner',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='s6',
            new_name='button_banner',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='s3_video',
            new_name='button_video',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='s1_description',
            new_name='button_video_description',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='s1_title',
            new_name='button_video_title',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='s2_description',
            new_name='middle_description',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='s2_title',
            new_name='middle_title',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='s5_video',
            new_name='middle_video',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='s3_video_description',
            new_name='middle_video_description',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='s3_video_title',
            new_name='middle_video_title',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='s5_video_description',
            new_name='top_description',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='s5_video_title',
            new_name='top_title',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='s7_video',
            new_name='up_video',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='s7_video_description',
            new_name='up_video_description',
        ),
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='s7_video_title',
            new_name='up_video_title',
        ),
    ]
