# Generated by Django 5.0.3 on 2024-03-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_bannerhomemodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactsubmitmodel',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='contactsubmitmodel',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
