# Generated by Django 5.0.2 on 2024-02-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_s4_banner_homesettingmodel_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesettingmodel',
            name='banner',
            field=models.ImageField(upload_to='images/home/', verbose_name='Section 6 Image'),
        ),
        migrations.AlterField(
            model_name='homesettingmodel',
            name='button_banner',
            field=models.ImageField(upload_to='images/home/', verbose_name='Section 4 Image'),
        ),
        migrations.AlterField(
            model_name='homesettingmodel',
            name='button_video',
            field=models.FileField(upload_to='videos/home', verbose_name='Section 7 Video'),
        ),
        migrations.AlterField(
            model_name='homesettingmodel',
            name='button_video_description',
            field=models.TextField(verbose_name='Section 7 Description'),
        ),
        migrations.AlterField(
            model_name='homesettingmodel',
            name='button_video_title',
            field=models.CharField(max_length=100, verbose_name='Section 7 Title'),
        ),
        migrations.AlterField(
            model_name='homesettingmodel',
            name='footer_image',
            field=models.ImageField(upload_to='images/home/footer', verbose_name='Section 8 Image'),
        ),
        migrations.AlterField(
            model_name='homesettingmodel',
            name='middle_description',
            field=models.TextField(verbose_name='Section 2 Description'),
        ),
        migrations.AlterField(
            model_name='homesettingmodel',
            name='middle_title',
            field=models.CharField(max_length=100, verbose_name='Section 2 Title'),
        ),
        migrations.AlterField(
            model_name='homesettingmodel',
            name='middle_video',
            field=models.FileField(upload_to='videos/home', verbose_name='Section 5 Video'),
        ),
        migrations.AlterField(
            model_name='homesettingmodel',
            name='middle_video_description',
            field=models.TextField(verbose_name='Section 5 Description'),
        ),
        migrations.AlterField(
            model_name='homesettingmodel',
            name='middle_video_title',
            field=models.CharField(max_length=100, verbose_name='Section 5 Title'),
        ),
        migrations.AlterField(
            model_name='homesettingmodel',
            name='top_description',
            field=models.TextField(verbose_name='Section 1 Description'),
        ),
        migrations.AlterField(
            model_name='homesettingmodel',
            name='top_title',
            field=models.CharField(max_length=100, verbose_name='Section 1 Title'),
        ),
        migrations.AlterField(
            model_name='homesettingmodel',
            name='up_video',
            field=models.FileField(upload_to='videos/home', verbose_name='Section 3 Video'),
        ),
        migrations.AlterField(
            model_name='homesettingmodel',
            name='up_video_description',
            field=models.TextField(verbose_name='Section 3 Description'),
        ),
        migrations.AlterField(
            model_name='homesettingmodel',
            name='up_video_title',
            field=models.CharField(max_length=100, verbose_name='Section 3 Title'),
        ),
    ]
