# Generated by Django 5.0.2 on 2024-03-10 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_addressmodel_active_address'),
        ('order', '0001_initial'),
        ('product', '0012_productcategorymodel_category_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitemmodel',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_size', to='product.sizeproductmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitemmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_order_item', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='address_order', to='accounts.addressmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='cart_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='error_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='ref_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='trace',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
