# Generated by Django 5.0.2 on 2024-03-08 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_addressmodel'),
        ('order', '0002_ordermodel_cart_id_ordermodel_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='address_order', to='accounts.addressmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
