# Generated by Django 5.0.2 on 2024-03-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_ordermodel_address_ordermodel_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='address',
        ),
    ]
