# Generated by Django 5.0.2 on 2024-03-08 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_addressmodel'),
        ('order', '0004_remove_ordermodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='address_order', to='accounts.addressmodel'),
            preserve_default=False,
        ),
    ]
