# Generated by Django 5.0.2 on 2024-03-16 08:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_ordermodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
