# Generated by Django 5.0.3 on 2024-04-12 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderitemmodel_created'),
        ('product', '0037_productvariantmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='product.productvariantmodel'),
        ),
    ]
