# Generated by Django 5.0.3 on 2024-04-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_orderitemmodel_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='item_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
