# Generated by Django 5.0.2 on 2024-03-10 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderitemmodel_completed'),
        ('product', '0012_productcategorymodel_category_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_color', to='product.colorproductmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitemmodel',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_size', to='product.sizeproductmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitemmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_order_item', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
