# Generated by Django 5.0.3 on 2024-04-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderitemmodel_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='trace',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
