# Generated by Django 5.0.2 on 2024-03-10 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderitemmodel_user'),
        ('product', '0012_productcategorymodel_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_size', to='product.sizeproductmodel'),
            preserve_default=False,
        ),
    ]
