# Generated by Django 5.0.2 on 2024-03-10 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_orderitemmodel_size'),
        ('product', '0012_productcategorymodel_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='color_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_color', to='product.colorproductmodel'),
            preserve_default=False,
        ),
    ]
