# Generated by Django 5.0.2 on 2024-03-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_orderitemmodel_color_orderitemmodel_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemmodel',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderitemmodel',
            name='size',
        ),
    ]
