# Generated by Django 5.0.2 on 2024-03-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orderitemmodel_color_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemmodel',
            name='color_product',
        ),
    ]
