# Generated by Django 5.0.2 on 2024-03-10 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_orderitemmodel_color_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItemModel',
        ),
    ]
